apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: jenkins/jenkins:docker:1.0
        name: container-0
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTS
            value: -Djenkins.install.runSetupWizard=false
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: false
          runAsUser: 0
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: nfs
          - mountPath: /var/run/docker.sock
            name: dockersock
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
          type: File
