apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-test
spec:
  storageClassName: "slow"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: pvc-test
  gcePersistentDisk:
    pdName: disk-test
    fsType: ext4
