apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-claim
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.128.0.57
    path: /mnt/nfs_share
    readOnly: false
